### ISSUE TITLE
Improve Styling of Terms of Use

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/Reflect.UP#136]
The Terms of Use can be improved by using html "h" and "p" and center" markup.

**Comment by alekiy** [comment]
https://github.com/University-of-Potsdam-MM/Reflect.UP/blob/master/www/js/index.js

**Comment by ManuTenorio** [comment]
The functions navigator.notification.confirm, and navigator.notification.alert of the cordova framework, accept only Strings as parameters, that cannot be further formated by means of HTML tags.
