### ISSUE TITLE
Dynamic load config.json from server over staticContent API

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/Reflect.UP#143]

**Comment by alekiy** [comment]
Endpoint: https://apiup.uni-potsdam.de/endpoints/staticContent/2.0/config.json

**Comment by ManuTenorio** [comment]
TODO:
use the cache - plugin to configure the frequency that the config.json file must be fetched from server (once per day)

**Comment by alekiy** [comment]
see caching function in #161
