### ISSUE TITLE
Two-stage multiple choice questions can be answered several times

### ISSUE THREAD

**Issue by olunczek** [University-of-Potsdam-MM/Reflect.UP#147]
Using a multiple choice question with two stages (1st question multiple answers with checkboxes, 2nd question single answers with radio button), I could answer it several times before it vanished from the quizzes overview.
A multiple choice question with just one stage/one question could be answered only once (as it should be), vanishing afterwards correctly.

**Comment by alekiy** [comment]
Updated local/reflect plugin after removing feedback_tracking. Should work now.

**Comment by olunczek** [comment]
Does not work, still possible to answer it multiple times. Tested on musang.

**Comment by alekiy** [comment]
- Multiple Choice - Single Answer muss noch implementiert werden

**Comment by ManuTenorio** [comment]
The problem detected, was that the answers for multiple choice questions (with checkboxes), were recorded as arrays of values. This conflicted with the expected value in "externalib.php":
'answer' => new external_value(PARAM_TEXT, 'Answer Text')
of the proyect:  "reflect-local"

The easiest way to correct this problem, was to send the answers with the following encoding:

   The array [1,2] which means that the first and second answers were selected, should be encoded and sent as the following string:   '|"text of first answer"|"text of second answer"

**Comment by ManuTenorio** [comment]
Changes commited to: 147-multiple-choice-questions-answers-as-string

**Comment by ManuTenorio** [comment]
TODO:  find out how the multiple choice answers (with checkboxes) are saved in the moodle database
