### ISSUE TITLE
Description of restricted Feedback Questions is displayed in only one language

### ISSUE THREAD

**Issue by olunczek** [University-of-Potsdam-MM/Reflect.UP#149]
If a question with restricted feedback is created, there appear two events in the calendar: The 1st for the time question opens for feedback and the 2nd event when the feedback time is closed.
The description of these events in the calender is EITHER in German OR in English but does not change. It seems that the English description is chosen when i create the restricted question with english set as own language and that the german description is chosen when German is set as language while creating  the event.
Even more bizarre: The description of ALL restricted questions change to english when I create (duplicate) a new restricted question with english set as language ... when i create afterwards a new restricted questions with german language, the description off ALL questions is displayed from then on in German ... 
(Just to clarify: The description language does not react to language settings (as it should), but to the creation of new restricted questions and the language chosen in this moment.)

**Comment by olunczek** [comment]
Now the description reads [object Object]
(Tested on musang)

**Comment by alekiy** [comment]
@olunczek restest plz

**Comment by olunczek** [comment]
Now the description is again just in one language (German). 
(Title changes correctly with language setting, description doesn't.)

**Comment by alekiy** [comment]
see #157 events for feedbacks are no longer displayed
