### ISSUE TITLE
model.js - processMoodleContents

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/Reflect.UP#151]
- Problem: duplicate defined
- extract function to new CollectionModel which is used by QuestionContainerList and AppointmentCollection

**Comment by ManuTenorio** [comment]
Ticket will be done again due to changes in processMoodleContents function + index.html

**Comment by ManuTenorio** [comment]
branch 151-processMoodleContents-duplicared    is ready to be merged
