### ISSUE TITLE
Generic method for css style modification

### ISSUE THREAD

**Issue by ManuTenorio** [University-of-Potsdam-MM/Reflect.UP#156]
Create variables in both "index.css" and "up-style.css" to do the style modification corresponding to a different university, simply by commenting different code sections.

**Comment by ManuTenorio** [comment]
TODO: manage different fonts

**Comment by alekiy** [comment]
add support for fonts  in sass files
https://stackoverflow.com/questions/1567184/sass-and-font-face

**Comment by alekiy** [comment]
To produce the css files use
1. `npm install` in the root directory
2. `cd script`
3. `../node_modules/.bin/gulp styles`

**Comment by ManuTenorio** [comment]
Working fine. To use the style of the European University Viadrina, the corresponding blocks in the "index.scss" file must be commented/un-commented, and the the command:
    gulp styles
must be executed. A new index.css file will be created.

**Comment by ManuTenorio** [comment]
final changes will be commited to new branch called:
164-convert-index.scss-to-css-with-gulp

**Comment by alekiy** [comment]
@ManuTenorio Status?

**Comment by ManuTenorio** [comment]
Status= finished
