### ISSUE TITLE
Implement Fallback for Configuration

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/Reflect.UP#167]
- [ ] on Error load local configuration
see https://stackoverflow.com/questions/17871129/backbonejs-collection-fetch-error-handler

**Comment by ManuTenorio** [comment]
Obs. : fetchError function has no use.

**Comment by alekiy** [comment]
Contact Page throws error when using fallback. Seems to use remote api endpoint instead locale model.

![image](https://user-images.githubusercontent.com/2682987/31809466-2bf86fbe-b578-11e7-8da2-a1a3e18b6504.png)

**Comment by ManuTenorio** [comment]
received and in process

**Comment by ManuTenorio** [comment]
changes commited to:  167-correct-contacts-url-before-fetch       ready to merge
