### ISSUE TITLE
Englische Übersetzung

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/Reflect.UP#18]
niedrig priorisiert

**Comment by alekiy** [comment]
Prüfen ob die verschiedenen Sprachen über die Schnittstelle kommen.
https://docs.moodle.org/28/en/Multi-language_content_filter

**Comment by ManuTenorio** [comment]
The application can now filter different languages from moodle contents.
The mechanism is a simple regex extraction using the tags:
<span lang="en" class="multilang">ENGLISH TEXT</span> 
<span lang="de" class="multilang">GERMAN TEXT</span>
