### ISSUE TITLE
Datenbank für gesendete Push-Nachrichten

### ISSUE THREAD

**Issue by lkstnr** [University-of-Potsdam-MM/Reflect.UP#208]

**Comment by alekiy** [comment]
> Wenn es dann soweit ist, dass die Reflect-App auf Kursebene genutzt werden kann, wird es dann auch möglich sein, in mehreren Kursen gleichzeitig angemeldet zu sein und entsprechend auch alle Termine einzusehen und alle Push-Nachrichten zu erhalten?
