### ISSUE TITLE
International Day Kurs

### ISSUE THREAD

**Issue by lkstnr** [University-of-Potsdam-MM/Reflect.UP#212]
> In diesem Jahr soll die App wieder auf dem International Day verwendet werden. Es gibt auch schon einen speziellen Kurs, den wir im letzten Jahr benutzt haben. Dieser sollte wieder so aktiviert werden, dass er über die App sichtbar ist. Am besten jedoch erst kurz vor dem International Day (15.11.18).

**Comment by alekiy** [comment]
@lkstnr Schau nun nochmal. ;)
