### ISSUE TITLE
Impressum-Seite überarbeiten

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/Reflect.UP#218]
Die Seite Impressum überarbeiten:
Titel - Neu : Impressum & Rechtliches

Hierzu eine Ion-List nutzen:
`  <ion-list>
    <ion-list-header>
      Impressum & Rechtliches
    </ion-list-header>
    <ion-item>
      Impressum
    </ion-item>
    <ion-item>
      Datenschutz
    </ion-item>
    <ion-item>
      Nutzungsbedingungen
    </ion-item>
  </ion-list>`

Die Inhalte aus der Config laden und entsprechend erweitern um
- impressumTemplateDE
- impressumTemplateEN
- dataprotectionTemplateDE
- dataprotectionTemplateDE
- tosTemplateDE
- tosTemplateEN

Für die drei Punkte jeweils Unterseiten erstellen. 

Die deutschen Inhalte habe ich bereits. Ein paar Übersetzungen stehen nun noch aus.

**Comment by alekiy** [comment]
@lkstnr Orientierung an DB-App. ;)

**Comment by lkstnr** [comment]
- [ ] restliche Texte einfügen
