### ISSUE TITLE
Kurse erstellen für SoSe19

### ISSUE THREAD

**Issue by rewolfpdm** [University-of-Potsdam-MM/Reflect.UP#226]
> Die Kurse für das kommende Sommersemester können schon im Moodle erstellt werden, sodass sie schon bearbeitet werden können.

**Comment by lkstnr** [comment]
Einige Kurse hat @alekiy schon angelegt, ggf. aber nicht alle?

**Comment by alekiy** [comment]
Erledigt. @rewolfpdm Ich habe dich in alle Kurse eingetragen. Die Kurse sind leer und haben als Startdatum den 1.04
