### ISSUE TITLE
Zugang aller Betreuenden zu GitHUB

### ISSUE THREAD

**Issue by rewolfpdm** [University-of-Potsdam-MM/Reflect.UP#228]
Haltet ihr es für eine sinnvolle Idee, wenn alle Kursbetreuenden Zugang zu der GitHUB-Seite bekommen und die anfallenden Probleme und Wünsche dann selbstständig eintragen? Oder ist euch der momentane Weg über mich lieber?

**Comment by lkstnr** [comment]
Ich glaube, Issues kann ja jeder eintragen, der hier angemeldet ist. Ob das jetzt über dich erfolgt oder alle das selbstständig machen, ist eigentlich egal.
