### ISSUE TITLE
AirNotifier Umstellung GCM - FCM

### ISSUE THREAD

**Issue by lkstnr** [University-of-Potsdam-MM/Reflect.UP#233]

**Comment by alekiy** [comment]
Vermutlich erledigt oder? :)

**Comment by lkstnr** [comment]
Ich hoffe, aber gänzlich abgeschaltet wird GCM erst am 29. Mai.

**Comment by lkstnr** [comment]
https://github.com/airnotifier/airnotifier/issues/199

**Comment by lkstnr** [comment]
Funktioniert grundsätzlich.
