### ISSUE TITLE
Reminder-Funktion für Termine

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/Reflect.UP#32]
Für von dem Nutzenden ausgewählte Termine die Möglichkeit zur Erinnerung / Reminderfunktion ermöglichen.

**Comment by rewolfpdm** [comment]
Dieser Punkt wurde auch wieder auf dem letzten Treffen (Dez. 18) angesprochen:
> Könnten für alle oder bestimmte Termine automatisch Erinnerungen an die Kursmitglieder verschickt werden?
