### ISSUE TITLE
App-Parameter konfigurierbar gestalten

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/Reflect.UP#53]
- [x] Login-URLs / Methoden
- [x] Impressum
- [x] Datenschutzerklärung
- [x] Theme
  - [x] Farbschema
  - [x] Logo

**Comment by ManuTenorio** [comment]
TODO: The "Kachelansicht" shown as the initial page can be further improved. (CSS3-flexboxes using grids for texts and images).
- the paths to the images to show are specified in their respective field on the file config.json
