### ISSUE TITLE
Hilfestellung im Kontext von MC-Fragen

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/Reflect.UP#57]
Wäre es möglich, einen funktionsfähigen Link in eine MC-Frage einzubauen? Also angenommen die Antworten wären _a) Ja, weiß ich._ und _b) Nein, weiß ich nicht._ Hinter die "b)-Antwort" in Klammern einen Hinweislink einzufügen, der dann auch funktioniert und direkt Hilfestellung bietet? Noch toller wäre es natürlich, dass er Hilfslink erst erschiene, wenn b) angeklickt werden würde, doch ich denke, dass ist zu kompliziert, oder?

**Comment by lkstnr** [comment]
Links in MC-Antworten funktionieren jetzt und werden geöffnet, wenn die Antwort ausgewählt wird.
