### ISSUE TITLE
Auftrennung von Nutzergruppen

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/Reflect.UP#63]
Eine Auswahl ermöglichen, dass man die zugehörige Fakultät auswählen kann.
Dahinter muss ein entsprechender Kurs stehen.
Hierzu sind Anpassungen am Webservice und der App notwendig.

**Comment by alekiy** [comment]
Einloggen, Kachelansicht (Fakultät, Studiengang, Kurs)

**Comment by ManuTenorio** [comment]
"Kachelansicht" is still to be correctly formatted with css3 flexboxes to show images next to course's title and descriptions.
