### ISSUE TITLE
Webservice und Kacheln erweitern

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/Reflect.UP#84]
- courseid für kacheln übertragbar
- Webservice erweitern

**Comment by ManuTenorio** [comment]
STEPS:
1. Contents of "Contact Persons page" must be hardcoded into the config.json file, and dynamically loaded to an empty template, same as in "Impressum".
2. The code of the program: externallib.php - must be modified to support different courses' ids when calling functions to get the events and feedbacks of a course.
     2.1 The plugin attached to the moodle site will need to have a list of the available courses' ids instead of just one.
     2.2 Every available course will have its corresponding ID correctly set.

**Comment by ManuTenorio** [comment]
This phase of development is done.
