### ISSUE TITLE
Multiple Choice werden als  Single Choice angezeigt

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/Reflect.UP#88]
überprüfen

**Comment by alekiy** [comment]
![test](https://cloud.githubusercontent.com/assets/2682987/26048516/bd0c3000-3957-11e7-90a0-3bfa015e471f.png)

**Comment by ManuTenorio** [comment]
Hi Alex!

    How are you doing?

    Regarding #88, I had already found a temporal solution to this issue. 
This solution had to do with using the 'label' FIELD of the feedback_item 
TABLE; the user had to give labels to the question with the prefixes "multi" 
or "single" for it to work. I guess you didn't like it very much :(
  
    Anyways, today I just found the right way to do it! Look at the 
following examples of the feedback_item TABLE:

stdClass Object
(
     [id] => 29
     [feedback] => 8
     [template] => 0
     [name] => Another Multiple choice - multiple answer
     [label] =>
     [presentation] => c>>>>>Europe
|America
|Asia
     [typ] => multichoice
     [hasvalue] => 1
     [position] => 2
     [required] => 0
     [dependitem] => 0
     [dependvalue] =>
     [options] => h
)

stdClass Object
(
     [id] => 30
     [feedback] => 8
     [template] => 0
     [name] => Multiple choice - single answer
     [label] =>
     [presentation] => r>>>>>Dinosaurs
|Aliens
|Zombies
     [typ] => multichoice
     [hasvalue] => 1
     [position] => 3
     [required] => 0
     [dependitem] => 0
     [dependvalue] =>
     [options] =>
)

stdClass Object
(
     [id] => 31
     [feedback] => 8
     [template] => 0
     [name] => Multiple choice - single answer allowed
     [label] =>
     [presentation] => d>>>>>Haha
|Hehe
|Hihi
     [typ] => multichoice
     [hasvalue] => 1
     [position] => 4
     [required] => 0
     [dependitem] => 0
     [dependvalue] =>
     [options] => h
)

  Whenever the user decides to create a new Multiple choice question within 
a Feedback (not to confuse with Quiz in the Moodle system), he must pick one 
of three possible types: Single answer, Multiple answer and single answer 
allowed. If you look at the examples above, can you tell what is the 
difference? Surely not the question type. There is an 'h' in the options 
field for the multiple answer and single answer allowed cases. The solution, 
however, is in the presentation field! And I am pretty sure that is how it 
gets implemented in Moodle;

r - for ratio button
c - for check box
d - for drop down list

Tomorrow I expect to close this ticket for good. See you then.
Manuel.

**Comment by ManuTenorio** [comment]
Solution submitted on ticket #118 Improve multiple answer question solution
