### ISSUE TITLE
Notification Multilingual

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/Reflect.UP#93]
Extend the Moodle block to send multilingual notification.

**Comment by alekiy** [comment]
- extend moodle block by two more inputs for title and msg, for english and espanol

![image](https://cloud.githubusercontent.com/assets/2682987/24698246/3be71cdc-19f0-11e7-9a32-dca7b066726e.png)

- [ ] send title and msg as new json object for example as

```
{"de": "Titel", "en": "title"
```

- [ ] check in Application which langugage is selected and display message and title for this langugage
- [ ] use as default language german if fields in moodle block are left blank

**Comment by ManuTenorio** [comment]
project located in:    https://github.com/University-of-Potsdam-MM/reflect-block_pushnotification

**Comment by ManuTenorio** [comment]
Comment line: 48 on coding: send_notification.php  - 
This will prevent all users from getting test messages.
