### ISSUE TITLE
Startseite / Kachelansicht stylen

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/Reflect.UP#95]
- [x] Kacheln müssen gleich hoch sein
- [x] Das Bild für die Fakultäten muss dort irgendwo rein passen / ggf. als Hintergrund
- [x] ggf. als einzelne Dropdowns damit genug Platz für Informaitionen ist?

**Comment by alekiy** [comment]
Einmal das Repo aktualisieren die Seite so wie die folgende noch aussehen. Farben gemäß des CI verwenden.

![test](https://cloud.githubusercontent.com/assets/2682987/24102571/b9b00f3c-0d7c-11e7-97db-1088fefd8b21.png)

**Comment by Clickmari** [comment]
Meine letzte Info war: Fakultätsfarben sind bald nicht mehr. Von Uni-logos würde ich absehen, erstens muss man sie jedes mal irgendwo her holen, zweitens haben die sehr unterschiedliche Formate. ich hab mal drei Sachen gemacht: Eine Listenansicht, eine Listenansicht mit geöffnetem Detail, Ansichtseinstellungen (je nachdem, wie viel da angeboten wird, is das ja langfristig imma ganz gut). Kacheln hab ich nicht genommen, weil ich nicht weiß, wie lang die Liste der Angebote da wird. Wenn man 20 Kurse hat, muss man nicht mit Kacheln anfangen. Filter oben drüber: müsst ihr wissen, ob das ein Filter mit Texteingabe oder lieber ein Select sein soll. 
![kurauswahl-settings](https://cloud.githubusercontent.com/assets/6390367/24295124/a632b034-1099-11e7-9d9d-57e008d96947.png)
![kursauswahl](https://cloud.githubusercontent.com/assets/6390367/24295122/a62c410e-1099-11e7-918e-0e5c5d17dce4.png)
![kursauswahl-detail](https://cloud.githubusercontent.com/assets/6390367/24295123/a63043ee-1099-11e7-949e-b7ff21fbf31f.png)

**Comment by alekiy** [comment]
Reicht zunächst wie implementiert.
